graph TB
  node_01K639J3RFDQR37P55DEX835VM["Unauthorized Access to Screenshots | [MED]"]:::mediumRisk
  node_01K639J3RFDQR37P55DEX835VM-1["Attacker exploits weak authentication mechanisms | [HIGH]"]:::highRisk
  node_01K639J3RFDQR37P55DEX835VM-1_cm_0["CM: Implement strong authentication mechanisms (Eff: 0.9)"]:::countermeasure
  node_01K639J3RFDQR37P55DEX835VM-2["Attacker gains access to the file system where screenshots are stored | [MED]"]:::mediumRisk
  node_01K639J3RFDQR37P55DEX835VM-2_cm_0["CM: Encrypt screenshots before saving (Eff: 0.85)"]:::countermeasure
  node_01K639J3RFDQR37P55DEX835VM-3["Attacker uses social engineering to obtain access | [MED]"]:::mediumRisk
  node_01K639J3RFDQR37P55DEX835VM-3_cm_0["CM: Conduct security awareness training for users (Eff: 0.75)"]:::countermeasure
  node_01K639J3RFDQR37P55DEX835VM_cm_0["CM: Regular security audits and vulnerability assessments (Eff: 0.8)"]:::countermeasure

  node_01K639J3RFDQR37P55DEX835VM --> node_01K639J3RFDQR37P55DEX835VM-1
  node_01K639J3RFDQR37P55DEX835VM-1 -.-> node_01K639J3RFDQR37P55DEX835VM-1_cm_0
  node_01K639J3RFDQR37P55DEX835VM --> node_01K639J3RFDQR37P55DEX835VM-2
  node_01K639J3RFDQR37P55DEX835VM-2 -.-> node_01K639J3RFDQR37P55DEX835VM-2_cm_0
  node_01K639J3RFDQR37P55DEX835VM --> node_01K639J3RFDQR37P55DEX835VM-3
  node_01K639J3RFDQR37P55DEX835VM-3 -.-> node_01K639J3RFDQR37P55DEX835VM-3_cm_0
  node_01K639J3RFDQR37P55DEX835VM -.-> node_01K639J3RFDQR37P55DEX835VM_cm_0

  classDef andNode fill:#FFB3B3,stroke:#8B0000,stroke-width:2px,color:#0B0D17
  classDef orNode fill:#C2FFD8,stroke:#106B49,stroke-width:2px,color:#0B0D17
  classDef leafNode fill:#73d1ff,stroke:#29ABE2,stroke-width:2px,color:#0B0D17
  classDef highRisk fill:#FFB3B3,color:#8B0000,stroke:#8B0000,stroke-width:2px
  classDef mediumRisk fill:#FFF200,stroke:#7A6300,stroke-width:1px,color:#0B0D17
  classDef lowRisk fill:#FFF2B3,stroke:#FFF2B3,stroke-width:1px,color:#0B0D17
  classDef countermeasure fill:#C2FFD8,stroke:#106B49,stroke-width:1px,color:#0B0D17
  classDef reference fill:#ffa1ad,stroke:#A259FF,stroke-width:1px,stroke-dasharray:3 3,color:#0B0D17
  classDef mitreNode stroke-dasharray:5 5
  classDef note fill:#ffffcc,stroke:#ffcc00,stroke-width:2px,stroke-dasharray:5 5