C4Context
    title Architecture Analysis - System Context
    Enterprise_Boundary(tb_User_Data_Boundary, "User Data Boundary") {
        System(Streamlit_Application, "Streamlit Application", "The frontend application built using Streamlit that interacts with users and displays the UI for authentication.")
        System(Authentication_Controller, "Authentication Controller", "Handles user authentication logic, including login, registration, and session management.")
        System(Configuration_File, "Configuration File", "Stores user credentials and application settings in a YAML format, including hashed passwords and OAuth2 parameters.")
    }
    System_Boundary(tb_External_Authentication_Boundary, "External Authentication Bou...") {
        System(Authentication_Controller, "Authentication Controller", "Handles user authentication logic, including login, registration, and session management.")
        System(OAuth2_Services, "OAuth2 Services", "Integrates with external OAuth2 providers (e.g., Google, Microsoft) for user authentication.")
    }
    System(Cookie_Management, "Cookie Management", "Manages cookies for session persistence and re-authentication, ensuring secure storage of user session data.")

    Rel(Streamlit_Application, Authentication_Controller, "Uses")
    Rel(Authentication_Controller, Cookie_Management, "Uses")
    Rel(Authentication_Controller, OAuth2_Services, "Uses")
    Rel(Configuration_File, Authentication_Controller, "Uses")