C4Context
    title Architecture Analysis - System Context
    System(End_Users, "End Users | Auth: OAuth 2.0, SAML | 🔒 | ⚠️", "Individuals who search for articles on the search page.")
    System(Amazon_OpenSearch, "Amazon OpenSearch | [AWS OpenSearch] | Auth: IAM roles | 🔒 | ⚠️", "Service used for retrieving search results based on user queries.")
    System(Amazon_API_Gateway, "Amazon API Gateway | [AWS API Gateway] | Auth: AWS IAM, Cognito | 🔒 | ⚠️", "Acts as a proxy to send search queries to backend services.")
    System(Amazon_Kinesis_Data_Streams, "Amazon Kinesis Data Streams | [AWS Kinesis] | Auth: IAM roles | 🔒 | ⚠️", "Streams search query logs for real-time processing.")
    System(Amazon_Kinesis_Firehose, "Amazon Kinesis Firehose | [AWS Kinesis Firehose] | Auth: IAM roles | 🔒 | ⚠️", "Consolidates search query logs every 15 minutes for storage.")
    System(AWS_Lambda, "AWS Lambda | [AWS Lambda] | Auth: IAM roles | 🔒 | ⚠️", "Functions that compress query logs and process CSV files for further analysis.")
    System(Amazon_S3, "Amazon S3 | [AWS S3] | Auth: IAM roles | 🔒 | ⚠️", "Storage service for raw logs, Parquet files, and clustered search queries.")
    System(AWS_Glue, "AWS Glue | [AWS Glue] | Auth: IAM roles | 🔒 | ⚠️", "Manages data cataloging and transformation, including creating tables and running jobs for data processing.")
    System(AWS_Step_Functions, "AWS Step Functions | [AWS Step Functions] | Auth: IAM roles | 🔒 | ⚠️", "Orchestrates workflows for trending query identification.")
    System(Amazon_Athena, "Amazon Athena | [AWS Athena] | Auth: IAM roles | 🔒 | ⚠️", "Queries data stored in S3 to retrieve top queries per cluster.")
    System(Amazon_Bedrock, "Amazon Bedrock | [AWS Bedrock] | Auth: IAM roles | 🔒 | ⚠️", "Utilized for identifying the most relevant search queries through machine learning.")
    SystemDb(Amazon_DynamoDB, "Amazon DynamoDB | [AWS DynamoDB] | Auth: IAM roles | 🔒 | ⚠️", "A NoSQL database that stores trending queries for quick retrieval.")

    Rel(End_Users, Amazon_API_Gateway, "HTTPS | Search Queries | Auth: required | 🔒 | ⚠️")
    Rel(Amazon_API_Gateway, Amazon_OpenSearch, "HTTPS | Search Queries | Auth: required | 🔒 | ⚠️")