C4Context
    title Architecture Analysis - System Context
    Enterprise_Boundary(tb_User_Data_Trust_Boundary, "User Data Trust Boundary") {
        System(End_Users, "End Users", "Auto-created component: End Users")
        System(Amazon_OpenSearch, "Amazon OpenSearch", "Service used for retrieving search results based on user queries.")
        System(Amazon_Kinesis_Data_Streams, "Amazon Kinesis Data Streams", "Streams search query logs for real-time processing.")
    }
    System_Boundary(tb_Data_Processing_Trust_Boundary, "Data Processing Trust Boundary") {
        System(AWS_Lambda, "AWS Lambda", "Serverless compute service that processes logs and invokes machine learning models.")
        SystemDb(Amazon_S3, "Amazon S3", "Storage service for raw logs and processed data.")
        SystemDb(Amazon_DynamoDB, "Amazon DynamoDB", "NoSQL database that stores the output of trending queries for quick retrieval.")
    }

    Rel(End_Users, Amazon_OpenSearch, "Uses")
    Rel(Amazon_OpenSearch, Amazon_Kinesis_Data_Streams, "Uses")
    Rel(Amazon_Kinesis_Data_Streams, Amazon_S3, "Uses")
    Rel(Amazon_S3, AWS_Lambda, "Uses")
    Rel(AWS_Lambda, Amazon_DynamoDB, "Uses")