graph TB
  node_01F8Z8G4E5F8D5B3F8AC["User | (user) | [UT]"]:::untrusted
  node_01F8Z8G4E5F8D5B3F8AD["GitHub | (service) | [UT]"]:::untrusted
  node_01F8Z8G4E5F8D5B3F8AE["Discord | (service) | [UT]"]:::untrusted
  node_01F8Z8G4E5F8D5B3F8A5["User Authentication | (api) | [HT]"]:::highTrust
  node_01F8Z8G4E5F8D5B3F8A6["Application Deployment | (backend) | [VHT]"]:::veryHighTrust
  node_01F8Z8G4E5F8D5B3F8A7["Database Management | (database) | [VHT]"]:::veryHighTrust
  node_01F8Z8G4E5F8D5B3F8A8["Monitoring Services | (service) | [LT]"]:::lowTrust
  node_01F8Z8G4E5F8D5B3F8A9["User Database | (database)"]:::dataStore
  node_01F8Z8G4E5F8D5B3F8AA["Application State Cache | (cache)"]:::dataStore
  node_01F8Z8G4E5F8D5B3F8AB["Backup Storage | (file)"]:::dataStore
  node_01F8Z8G4E5F8D5B3F8A2["User Data | [PII]"]:::dataAsset,pii
  node_01F8Z8G4E5F8D5B3F8A3["Application Configurations | [INT]"]:::dataAsset,internal
  node_01F8Z8G4E5F8D5B3F8A4["Database Backups | [CONF]"]:::dataAsset,confidential

  node_01F8Z8G4E5F8D5B3F8AC -->|User Authentication Data| node_01F8Z8G4E5F8D5B3F8A5:::encryptedFlow
  node_01F8Z8G4E5F8D5B3F8A5 -->|Deployment Commands| node_01F8Z8G4E5F8D5B3F8A6:::unencryptedFlow
  node_01F8Z8G4E5F8D5B3F8A6 -->|Database Queries| node_01F8Z8G4E5F8D5B3F8A7:::unencryptedFlow
  node_01F8Z8G4E5F8D5B3F8A7 -->|Monitoring Data| node_01F8Z8G4E5F8D5B3F8A8:::unencryptedFlow

  classDef externalEntity fill:#FF4C4C,stroke:#FF4C4C,stroke-width:2px,color:#F5F7FA
  classDef process fill:#36FF8F,stroke:#36FF8F,stroke-width:2px,color:#0B0D17
  classDef dataStore fill:#29ABE2,stroke:#29ABE2,stroke-width:2px,color:#F5F7FA
  classDef dataAsset fill:#A259FF,stroke:#c3a4ff,stroke-width:2px,color:#F5F7FA
  classDef untrusted fill:#FF4C4C,stroke:#FF4C4C,stroke-width:3px,stroke-dasharray:5 5
  classDef lowTrust fill:#f77c63,stroke:#f77c63,stroke-width:2px,stroke-dasharray:3 3
  classDef mediumTrust fill:#FFD300,stroke:#FFD300,stroke-width:2px
  classDef highTrust fill:#C2FFD8,stroke:#36FF8F,stroke-width:2px
  classDef veryHighTrust fill:#36FF8F,stroke:#36FF8F,stroke-width:3px
  classDef public fill:#C2FFD8,stroke:#36FF8F,stroke-width:1px
  classDef internal fill:#FFF2B3,stroke:#FFD300,stroke-width:1px
  classDef confidential fill:#FFB3B3,stroke:#FF4C4C,stroke-width:2px
  classDef restricted fill:#FF4C4C,stroke:#FF4C4C,stroke-width:3px
  classDef pii fill:#ffa1ad,stroke:#A259FF,stroke-width:2px
  classDef pci fill:#FF4C4C,stroke:#FF4C4C,stroke-width:3px
  classDef phi fill:#ffa1ad,stroke:#A259FF,stroke-width:3px
  classDef encryptedFlow stroke:#36FF8F,stroke-width:2px
  classDef unencryptedFlow stroke:#FF4C4C,stroke-width:2px,stroke-dasharray:5 5
  classDef authenticatedFlow stroke:#29ABE2,stroke-width:2px
  classDef trustBoundary fill:transparent,stroke:#2E3440,stroke-width:3px,stroke-dasharray:10 5