graph TB
  node_01K64NS1J5Z7XCZSH32AFMGWTP["Unauthorized Access to Dokploy Application | [HIGH]"]:::highRisk
  node_01K64NS1J5Z7XCZSH32AFMGWTP-1["Weak Passwords | [MED]"]:::mediumRisk
  node_01K64NS1J5Z7XCZSH32AFMGWTP-1_cm_0["CM: Implement strong password policies. (Eff: 0.8)"]:::countermeasure
  node_01K64NS1J5Z7XCZSH32AFMGWTP-1_cm_1["CM: Enable multi-factor authentication (MFA). (Eff: 0.9)"]:::countermeasure
  node_01K64NS1J5Z7XCZSH32AFMGWTP-2["Phishing Attacks | [HIGH]"]:::highRisk
  node_01K64NS1J5Z7XCZSH32AFMGWTP-2_cm_0["CM: Conduct regular security awareness training. (Eff: 0.7)"]:::countermeasure
  node_01K64NS1J5Z7XCZSH32AFMGWTP-2_cm_1["CM: Implement email filtering and anti-phishing tools. (Eff: 0.75)"]:::countermeasure
  node_01K64NS1J5Z7XCZSH32AFMGWTP-3["Session Hijacking | [HIGH]"]:::highRisk
  node_01K64NS1J5Z7XCZSH32AFMGWTP-3_cm_0["CM: Use secure cookies and HTTPS. (Eff: 0.85)"]:::countermeasure
  node_01K64NS1J5Z7XCZSH32AFMGWTP-3_cm_1["CM: Implement session timeout and re-authentication. (Eff: 0.8)"]:::countermeasure
  node_01K64NS1J5Z7XCZSH32AFMGWTP_cm_0["CM: Regularly update and patch software components. (Eff: 0.9)"]:::countermeasure
  node_01K64NS1J5Z7XCZSH32AFMGWTP_cm_1["CM: Conduct security audits and penetration testing. (Eff: 0.85)"]:::countermeasure

  node_01K64NS1J5Z7XCZSH32AFMGWTP -.-> node_01K64NS1J5Z7XCZSH32AFMGWTP-1
  node_01K64NS1J5Z7XCZSH32AFMGWTP-1 -.-> node_01K64NS1J5Z7XCZSH32AFMGWTP-1_cm_0
  node_01K64NS1J5Z7XCZSH32AFMGWTP-1 -.-> node_01K64NS1J5Z7XCZSH32AFMGWTP-1_cm_1
  node_01K64NS1J5Z7XCZSH32AFMGWTP -.-> node_01K64NS1J5Z7XCZSH32AFMGWTP-2
  node_01K64NS1J5Z7XCZSH32AFMGWTP-2 -.-> node_01K64NS1J5Z7XCZSH32AFMGWTP-2_cm_0
  node_01K64NS1J5Z7XCZSH32AFMGWTP-2 -.-> node_01K64NS1J5Z7XCZSH32AFMGWTP-2_cm_1
  node_01K64NS1J5Z7XCZSH32AFMGWTP -.-> node_01K64NS1J5Z7XCZSH32AFMGWTP-3
  node_01K64NS1J5Z7XCZSH32AFMGWTP-3 -.-> node_01K64NS1J5Z7XCZSH32AFMGWTP-3_cm_0
  node_01K64NS1J5Z7XCZSH32AFMGWTP-3 -.-> node_01K64NS1J5Z7XCZSH32AFMGWTP-3_cm_1
  node_01K64NS1J5Z7XCZSH32AFMGWTP -.-> node_01K64NS1J5Z7XCZSH32AFMGWTP_cm_0
  node_01K64NS1J5Z7XCZSH32AFMGWTP -.-> node_01K64NS1J5Z7XCZSH32AFMGWTP_cm_1

  classDef andNode fill:#FFB3B3,stroke:#8B0000,stroke-width:2px,color:#0B0D17
  classDef orNode fill:#C2FFD8,stroke:#106B49,stroke-width:2px,color:#0B0D17
  classDef leafNode fill:#73d1ff,stroke:#29ABE2,stroke-width:2px,color:#0B0D17
  classDef highRisk fill:#FFB3B3,color:#8B0000,stroke:#8B0000,stroke-width:2px
  classDef mediumRisk fill:#FFF200,stroke:#7A6300,stroke-width:1px,color:#0B0D17
  classDef lowRisk fill:#FFF2B3,stroke:#FFF2B3,stroke-width:1px,color:#0B0D17
  classDef countermeasure fill:#C2FFD8,stroke:#106B49,stroke-width:1px,color:#0B0D17
  classDef reference fill:#ffa1ad,stroke:#A259FF,stroke-width:1px,stroke-dasharray:3 3,color:#0B0D17
  classDef mitreNode stroke-dasharray:5 5
  classDef note fill:#ffffcc,stroke:#ffcc00,stroke-width:2px,stroke-dasharray:5 5