graph TB
  node_01F8V8F5J0R8D3F8K9F8B8F8E0["End User | (user) | [UT]"]:::untrusted
  node_01F8V8F5J0R8D3F8K9F8B8F8E1["Azure Active Directory | (service) | [UT]"]:::untrusted
  node_01F8V8F5J0R8D3F8K9F8B8F8P0["User Authentication | (api) | [VHT]"]:::veryHighTrust
  node_01F8V8F5J0R8D3F8K9F8B8F8P1["Request Processing | (backend) | [HT]"]:::highTrust
  node_01F8V8F5J0R8D3F8K9F8B8F8P2["Background Processing | (service) | [LT]"]:::lowTrust
  node_01F8V8F5J0R8D3F8K9F8B8F8D0["Azure SQL Database | (database)"]:::dataStore
  node_01F8V8F5J0R8D3F8K9F8B8F8J9["User Data | [PII]"]:::dataAsset,pii
  node_01F8V8F5J0R8D3F8K9F8B8F8J0["Application Logs | [INT]"]:::dataAsset,internal
  node_01F8V8F5J0R8D3F8K9F8B8F8J1["Configuration Secrets | [REST]"]:::dataAsset,restricted

  node_01F8V8F5J0R8D3F8K9F8B8F8E0 -->|User Request to Application Gateway| node_01F8V8F5J0R8D3F8K9F8B8F8P0:::encryptedFlow
  node_01F8V8F5J0R8D3F8K9F8B8F8P1 -->|Request to Azure SQL Database| node_01F8V8F5J0R8D3F8K9F8B8F8D0:::unencryptedFlow
  node_01F8V8F5J0R8D3F8K9F8B8F8P1 -->|Logs to Application Insights| node_01F8V8F5J0R8D3F8K9F8B8F8P2:::encryptedFlow

  classDef externalEntity fill:#FF4C4C,stroke:#FF4C4C,stroke-width:2px,color:#F5F7FA
  classDef process fill:#36FF8F,stroke:#36FF8F,stroke-width:2px,color:#0B0D17
  classDef dataStore fill:#29ABE2,stroke:#29ABE2,stroke-width:2px,color:#F5F7FA
  classDef dataAsset fill:#A259FF,stroke:#c3a4ff,stroke-width:2px,color:#F5F7FA
  classDef untrusted fill:#FF4C4C,stroke:#FF4C4C,stroke-width:3px,stroke-dasharray:5 5
  classDef lowTrust fill:#f77c63,stroke:#f77c63,stroke-width:2px,stroke-dasharray:3 3
  classDef mediumTrust fill:#FFD300,stroke:#FFD300,stroke-width:2px
  classDef highTrust fill:#C2FFD8,stroke:#36FF8F,stroke-width:2px
  classDef veryHighTrust fill:#36FF8F,stroke:#36FF8F,stroke-width:3px
  classDef public fill:#C2FFD8,stroke:#36FF8F,stroke-width:1px
  classDef internal fill:#FFF2B3,stroke:#FFD300,stroke-width:1px
  classDef confidential fill:#FFB3B3,stroke:#FF4C4C,stroke-width:2px
  classDef restricted fill:#FF4C4C,stroke:#FF4C4C,stroke-width:3px
  classDef pii fill:#ffa1ad,stroke:#A259FF,stroke-width:2px
  classDef pci fill:#FF4C4C,stroke:#FF4C4C,stroke-width:3px
  classDef phi fill:#ffa1ad,stroke:#A259FF,stroke-width:3px
  classDef encryptedFlow stroke:#36FF8F,stroke-width:2px
  classDef unencryptedFlow stroke:#FF4C4C,stroke-width:2px,stroke-dasharray:5 5
  classDef authenticatedFlow stroke:#29ABE2,stroke-width:2px
  classDef trustBoundary fill:transparent,stroke:#2E3440,stroke-width:3px,stroke-dasharray:10 5