graph TB
  node_01FCNDV6P593Q68X68946X6905["User | (user) | [UT]"]:::untrusted
  node_01FCNDV6P593Q68X68946X6906["Linux system | (system) | [UT]"]:::untrusted
  node_01FCNDV6P593Q68X68946X6900["AppImageKit service | (service) | [HT]"]:::highTrust
  node_01FCNDV6P593Q68X68946X6901["Build process | (backend) | [HT]"]:::highTrust
  node_01FCNDV6P593Q68X68946X6902["User interface | (frontend) | [LT]"]:::lowTrust
  node_01FCNDV6P593Q68X68946X6903["Build cache | (cache)"]:::dataStore
  node_01FCNDV6P593Q68X68946X6904["Configuration storage | (file)"]:::dataStore
  node_01FCNDV6P593Q68X68946X6895["AppImage file | [CONF]"]:::dataAsset,confidential
  node_01FCNDV6P593Q68X68946X6896["Source code | [INT]"]:::dataAsset,internal
  node_01FCNDV6P593Q68X68946X6897["Configuration files | [INT]"]:::dataAsset,internal
  node_01FCNDV6P593Q68X68946X6898["User data | [PII]"]:::dataAsset,pii
  node_01FCNDV6P593Q68X68946X6899["Build logs | [INT]"]:::dataAsset,internal


  classDef externalEntity fill:#FFB3B3,stroke:#8B0000,stroke-width:2px,color:#0B0D17
  classDef process fill:#C2FFD8,stroke:#106B49,stroke-width:2px,color:#0B0D17
  classDef dataStore fill:#73d1ff,stroke:#29ABE2,stroke-width:2px,color:#0B0D17
  classDef dataAsset fill:#ffa1ad,stroke:#A259FF,stroke-width:2px,color:#0B0D17
  classDef untrusted fill:#FFB3B3,stroke:#8B0000,stroke-width:3px,stroke-dasharray:5 5
  classDef lowTrust fill:#f77c63,stroke:#f77c63,stroke-width:2px,stroke-dasharray:3 3
  classDef mediumTrust fill:#FFF2B3,stroke:#7A6300,stroke-width:2px
  classDef highTrust fill:#C2FFD8,stroke:#106B49,stroke-width:2px
  classDef veryHighTrust fill:#36FF8F,stroke:#36FF8F,stroke-width:3px
  classDef public fill:#C2FFD8,stroke:#106B49,stroke-width:1px
  classDef internal fill:#FFF2B3,stroke:#7A6300,stroke-width:1px
  classDef confidential fill:#FFB3B3,stroke:#8B0000,stroke-width:2px
  classDef restricted fill:#8B0000,stroke:#8B0000,stroke-width:3px
  classDef pii fill:#ffa1ad,stroke:#A259FF,stroke-width:2px
  classDef pci fill:#8B0000,stroke:#8B0000,stroke-width:3px
  classDef phi fill:#ffa1ad,stroke:#A259FF,stroke-width:3px
  classDef encryptedFlow stroke:#106B49,stroke-width:2px
  classDef unencryptedFlow stroke:#8B0000,stroke-width:2px,stroke-dasharray:5 5
  classDef authenticatedFlow stroke:#29ABE2,stroke-width:2px
  classDef trustBoundary fill:transparent,stroke:#2E3440,stroke-width:3px,stroke-dasharray:10 5