C4Context
    title Architecture Analysis - System Context
    Enterprise_Boundary(tb_User_Data_Trust_Boundary, "User Data Trust Boundary") {
        System(Web_Servers, "Web Servers", "Handle incoming requests and serve dynamic content.")
        SystemDb(Amazon_RDS, "Amazon RDS", "Manages relational databases, ensuring data persistence and availability.")
    }
    System_Boundary(tb_Static_Content_Trust_Boundary, "Static Content Trust Boundary") {
        SystemDb(Amazon_S3_Bucket, "Amazon S3 Bucket", "Stores static assets such as images and files, accessible via the application.")
    }
    System(Amazon_Route_53, "Amazon Route 53", "A DNS service that directs traffic to the application.")
    System(Elastic_Load_Balancer__ELB_, "Elastic Load Balancer (ELB)", "Distributes incoming application traffic across multiple web servers to ensure no single server is overwhelmed.")

    Rel(Amazon_Route_53, Elastic_Load_Balancer__ELB_, "Uses")
    Rel(Elastic_Load_Balancer__ELB_, Web_Servers, "Uses")
    Rel(Web_Servers, Amazon_RDS, "Uses")
    Rel(Web_Servers, Amazon_S3_Bucket, "Uses")