C4Context
    title Architecture Analysis - System Context
    Enterprise_Boundary(tb_User_Device_Trust_Boundary, "User Device Trust Boundary") {
        System(Screengrab, "Screengrab", "A component responsible for capturing screenshots of mobile applications using different strategies.")
        System(ScreenshotStrategy, "ScreenshotStrategy", "An interface that defines the method for taking screenshots, allowing for various implementations like DecorViewScreenshotStrategy and UiAutomatorS...")
    }
    System(FileWritingScreenshotCallback, "FileWritingScreenshotCallback", "Handles the saving of captured screenshots to the file system, ensuring proper file management and directory structure.")

    Rel(Screengrab, ScreenshotStrategy, "Uses")
    Rel(ScreenshotStrategy, FileWritingScreenshotCallback, "Uses")