C4Context
    title Architecture Analysis - System Context
    Enterprise_Boundary(tb_User_Device_Trust_Boundary, "User Device Trust Boundary") {
        System(Screengrab, "Screengrab", "A component responsible for capturing screenshots of Android applications.")
        System(ScreenshotStrategy, "ScreenshotStrategy", "An interface defining various strategies for taking screenshots, including different methods like DecorView and UiAutomator.")
        System(FileWritingScreenshotCallback, "FileWritingScreenshotCallback", "Handles the saving of captured screenshots to the file system.")
    }
    System(CleanStatusBar, "CleanStatusBar", "Manages the status bar appearance during screenshot capture to ensure a clean output.")

    Rel(Screengrab, ScreenshotStrategy, "Uses")
    Rel(ScreenshotStrategy, FileWritingScreenshotCallback, "Uses")
    Rel(FileWritingScreenshotCallback, CleanStatusBar, "Uses")