C4Context
    title Architecture Analysis - System Context
    Enterprise_Boundary(tb_User_Access_Boundary, "User Access Boundary") {
        System(Application_Gateway, "Application Gateway", "Acts as a reverse proxy to manage incoming traffic and distribute it to backend services.")
        System(Web_App_Firewall, "Web App Firewall", "Provides protection against common web vulnerabilities.")
    }
    System_Boundary(tb_Data_Storage_Boundary, "Data Storage Boundary") {
        System(Web_App, "Web App", "Auto-created component: Web App")
        SystemDb(Azure_SQL_Database, "Azure SQL Database", "Stores application data securely.")
    }
    System(Load_Balancers, "Load Balancers", "Distributes incoming traffic across multiple instances of the web application for improved availability and performance.")
    System(Application_Insights, "Application Insights", "Monitors application performance and usage.")
    System(Users, "Users", "Auto-created component: Users")

    Rel(Users, Application_Gateway, "Uses")
    Rel(Application_Gateway, Web_App_Firewall, "Uses")
    Rel(Web_App_Firewall, Load_Balancers, "Uses")
    Rel(Web_App, Azure_SQL_Database, "Uses")
    Rel(Web_App, Application_Insights, "Uses")